### ISSUE TITLE
Single quotes in select value are not escaped

### ISSUE THREAD

**Issue by eturk** [markjs/jquery-dependent-selects#18]
I have a `select` tag that looks like this:

```html
<option value='53d50e187461729bc7000000'>Men's > Clothing > Tops > Shirts</option>
```

This causes jquery-dependent-selects to error out because it uses single quotes as well:

```
Uncaught Error: Syntax error, unrecognized expression: select[data-dependent-parent='Men's'][data-dependent-id='449']
```

**Comment by markjs** [comment]
Hey @eturk and @ajquick! I've just had this repo transferred back to me from my previous employer (I originally created it while working there). Over the coming days and weeks I'll be catching up with all the issues and looking into personally maintaining this in the long run.

Sorry that your comments have gone un-replied for so long, but now it's back in my hands I'll try my best to stay on top of it all.

**Comment by rvernica** [comment]
See #23 for pull request which might fix this.
